### PR TITLE
[Add] testing hooks

### PR DESCRIPTION
**Pull request by chris-addison**

### CODE REVIEW

**Comment by djdupre** [comment]
I don't like how these testing hooks require us to spam null checks everywhere. Can we instead separate the code that fetches the raw JSON into another file? I think something like this would be nice:
```Kotlin
class GoogleCodePlugin(projectName: String, private val api: GoogleCodeAPI = GoogleCodeDefaultAPI(projectName)) : Plugin { ... }
```
Then when we want to test we pass in a dummy API that gives back raw JSON.

**Comment by chris-addison** [comment]
Yeah, I can do that tomorrow. That's a much better idea.

**Comment by djdupre** [comment]
I'll do it for the Google Code plugin

**Comment by chris-addison** [comment]
Should we make a general api interface, or one for each plugin?

**Comment by djdupre** [comment]
I think each plugin may need its own unique api interface. For example Google Code needs a fetchIssuesPage function but other plugins probably do not.

**Comment by chris-addison** [comment]
That's true. Then, specific for each plugin it is.

**Comment by chris-addison** [comment]
I've finished porting the code. Feel free to take a look!

**Pull request merged**
